version: '3.8'

services:
  backend:
    image: realprojeeeeet-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
      - ./frontend/.env
    restart: unless-stopped

  frontend:
    image: realprojeeeeet-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Maps localhost:3000 to container port 80
    depends_on:
      - backend
    restart: unless-stopped
